# Generated by Django 5.1.6 on 2025-02-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('id_dosen', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nid', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
