# Generated by Django 5.1.6 on 2025-02-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='name',
            new_name='nama_dosen',
        ),
    ]
