# Generated by Django 5.1.6 on 2025-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_rename_name_dosen_nama_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
