# Generated by Django 5.1.6 on 2025-02-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0001_initial'),
        ('matakuliah', '0002_rename_mahasiswa_matakuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='kelas',
            fields=[
                ('id_kelas', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('nama_kelas', models.CharField(max_length=60, unique=True)),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen.dosen')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matakuliah.matakuliah')),
            ],
        ),
    ]
