# Generated by Django 5.1.6 on 2025-02-25 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id_matkul', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('nama_matkul', models.CharField(max_length=60, unique=True)),
                ('sks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen.dosen')),
            ],
        ),
    ]
