# Generated by Django 5.1.6 on 2025-02-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
        ('matakuliah', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mahasiswa',
            new_name='matakuliah',
        ),
    ]
