# Generated by Django 5.1.6 on 2025-02-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0002_rename_mahasiswa_matakuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='sks',
            field=models.IntegerField(default=0),
        ),
    ]
