# Generated by Django 5.1.6 on 2025-02-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrasi',
            fields=[
                ('id_nilai', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_registrasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrasi.registrasi')),
            ],
        ),
    ]
