# Generated by Django 5.1.6 on 2025-02-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
        ('registrasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrasi',
            new_name='nilai',
        ),
    ]
