# Generated by Django 5.1.6 on 2025-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0002_rename_registrasi_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='file_nilai',
            field=models.ImageField(blank=True, null=True, upload_to='nilai/'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
    ]
