# Generated by Django 5.1.6 on 2025-02-28 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0003_nilai_file_nilai_alter_nilai_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='file_nilai',
            field=models.ImageField(blank=True, default='', upload_to='nilai/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
