# Generated by Django 5.1.6 on 2025-02-25 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurusan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id_mahasiswa', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=60, unique=True)),
                ('nim', models.CharField(max_length=255, unique=True)),
                ('id_jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.jurusan')),
            ],
        ),
    ]
