# Generated by Django 5.1.6 on 2025-02-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
