# Generated by Django 5.1.6 on 2025-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
