# Generated by Django 5.1.6 on 2025-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jurusan',
            fields=[
                ('id_jurusan', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('nama_jurusan', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
