# Generated by Django 5.1.6 on 2025-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurusan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='id_jurusan',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
